---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    loopback_users.rabbitmqUser = false
    default_vhost = /
    #management.load_definitions = /etc/rabbitmq/definitions.json # Not working
  definitions.json: |
    {
      "users": [],
      "vhosts": [  { "name": "/"  } ],
      "permissions": [],
      "parameters": [],
      "policies": [  {"vhost":"/","name":"DLX","pattern":".*","apply-to":"queues","definition":{"dead-letter-exchange":"dead-letter.exchange"},"priority":0}],
      "queues": [
        {"name":"store-domain-queue","vhost":"/","durable":true,"auto_delete":false,"arguments":{}},
        {"name":"store-domain-queue.dead-letter","vhost":"/","durable":true,"auto_delete":false,"arguments":{}}
      ],
      "exchanges": [
        {"name":"stores.exchange","vhost":"/","type":"topic","durable":true,"auto_delete":false,"internal":false,"arguments":{}}
      ],
      "bindings": [
        {"source":"stores.exchange","vhost":"/","destination":"store-domain-queue","destination_type":"queue","routing_key":"internal","arguments":{}},
      ]
    }
  enabled_plugins: |
    [rabbitmq_prometheus, rabbitmq_amqp1_0, rabbitmq_management, rabbitmq_web_dispatch, rabbitmq_management_agent, rabbitmq_stomp].
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: rabbitmq-port
        - containerPort: 15672
          name: rab-mngt-port
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        volumeMounts:
        - name: definitions-json
          mountPath: /etc/rabbitmq/definitions.json
          subPath: definitions.json
        - name: rabbitmq-config-file
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: enabled-plugins
          mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins  
        volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: definitions-json
          configMap:
            name: rabbitmq-config
            items:
              - key: definitions.json
                path: definitions.json
        - name: rabbitmq-config-file
          configMap:
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
        - name: enabled-plugins
          configMap:
            name: rabbitmq-config
            items:
              - key: enabled_plugins
                path: enabled_plugins     
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rab-mngt-port
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer-srv
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rab-mngt-port
      protocol: TCP
      port: 15672
      targetPort: 15672